apiVersion: v1
kind: Service
metadata:
  name: {{ include "diss-app-web.fullname" . }}
  labels:
    {{- include "diss-app-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: predictor-port
  selector:
    {{- include "diss-app-web.selectorLabels" . | nindent 4 }}
