version: '3.7'

services:
  ml_base:
    build:
      context: images/airflow-ml-base
    image: airflow-ml-base

  predict:
    build:
      context: images/airflow-predict
    image: airflow-predict

  download:
    build:
      context: images/airflow-download
    image: airflow-download

  eda:
    build:
      context: images/airflow-eda
    image: airflow-eda

  split:
    build:
      context: images/airflow-split
    image: airflow-split

  preprocess:
    build:
      context: images/airflow-preprocess
    image: airflow-preprocess