# @package _group_
path_zip: ./data/data.zip
out_path_test: ./data/train-test/train.csv
out_path_train: ./data/train-test/test.csv
split_params:
  random_state: 43
  train_size: 0.8
target_variable: target
