apiVersion: v1
kind: Pod
metadata:
  name: simple-web-resources
spec:
  containers:
    - name: web-predictor
      image: kernela/hear-diss-app
      ports:
        - name: predictor-port
          containerPort: 8000
      resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "100Mi"