apiVersion: v1
kind: Service
metadata:
  name: web-gateway
spec:
  ports:
      - port: 9000
        targetPort: predictor-port
  type: NodePort
  selector:
    app: predictor-web-instance

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-deploy-crashing
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  replicas: 2
  selector:
    matchLabels:
      app: predictor-web-instance
  template:
    metadata:
      labels:
        app: predictor-web-instance
    spec:
      containers:
        - name: web-predictor
          image: kernela/hear-diss-app
          ports:
            - name: predictor-port
              containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "100Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: predictor-port
            failureThreshold: 1
            periodSeconds: 10
            initialDelaySeconds: 25
          readinessProbe:
            tcpSocket:
              port: predictor-port
            initialDelaySeconds: 20
            periodSeconds: 10