stages:
  generate-report:
    cmd: python ./generate_report.py --config ./configs/report_config.yml
    deps:
      - ./configs/report_config.yml
      - ./data/data.zip
      - ./generate_report.py
    outs:
      - ./data/report/eda.html:
          cache: false
          persist: true
