stages:
  generate-report:
    cmd: python ./genrate_report.py --config ./configs/report_config.yml
    deps:
    - ./configs/report_config.yml
    - ./data/data.zip
    - ./genrate_report.py
    outs:
    - ./data/report/eda.html:
        cache: false
