stages:
  generate-report:
    cmd: python ./generate_report.py -cd ./configs
    deps:
      - ./configs/report_config.yaml
      - ./data/data.zip
      - ./generate_report.py
    outs:
      - ./data/report/eda.html:
          cache: false
          persist: true
  train-log-reg:
    cmd: python ./train.py -cd ./configs/train -cn train_log_reg
    deps:
      - ./config.py
      - ./heat_diss
      - ./train.py
      - ./data/train-test
      - ./configs/train/train_log_reg.yaml
    metrics:
      - ./data/train/log_reg/log_reg_metrics.json
    plots:
      - ./data/train/log_reg/conf_matrix.csv
    outs:
      - ./data/train/log_reg/model.pickle
  train-svc:
    cmd: python ./train.py -cd ./configs/train -cn train_svc
    deps:
      - ./config.py
      - ./heat_diss
      - ./train.py
      - ./data/train-test
      - ./configs/train/train_svc.yaml
    metrics:
      - ./data/train/svc/svc_metrics.json
    plots:
      - ./data/train/svc/conf_matrix.csv
    outs:
      - ./data/train/svc/model.pickle
  train-test-split:
    cmd: python ./train_test_split.py -cd ./configs/train_test_split
    deps:
      - ./config.py
      - ./configs/train_test_split/train_test_split.yaml
      - ./data/data.zip
      - ./train_test_split.py
    outs:
      - ./data/train-test
  log-reg-predict:
    cmd: python ./predict.py -cd ./configs -cn ./predict_log_reg
    deps:
      - ./predict.py
      - ./config.py
      - ./configs/predict_log_reg.yaml
      - ./data/train/log_reg/model.pickle
      - ./data/train-test
    outs:
      - ./data/test-prediction/prediction.csv
  log-reg-plot-conf-matrix:
    cmd: python ./plot_conf_matrix.py -cd ./configs title="Logistic regression confusion matrix"
    deps:
      - ./config.py
      - ./plot_conf_matrix.py
      - ./configs/plot_conf_matrix.yaml
      - ./data/train/log_reg/conf_matrix.csv
    outs:
      - ./data/train/log_reg/conf_matrix.png
  svc-plot-conf-matrix:
    cmd: python ./plot_conf_matrix.py -cd ./configs train=train_svc title="SVC confusion matrix" output_image=./data/train/svc/conf_matrix.png
    deps:
      - ./config.py
      - ./plot_conf_matrix.py
      - ./configs/plot_conf_matrix.yaml
      - ./data/train/svc/conf_matrix.csv
    outs:
      - ./data/train/svc/conf_matrix.png
